name: Enforce Pull Request Usage
on:
  push:
    branches:
      - main

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is from fromm a pull request
        if: github.event_name == 'push' && github.actor != 'github-actions'
        run: |
          echo "Direct pushes to the main branch are not allowed. Please use pull requests."
          exit 1
